name: Setup New Directory
on:
  workflow_dispatch:
  schedule:
    - cron: "11 1 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 12 *"
jobs:
  dir_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create New Directory
        run: |
          mkdir day$(date +%d)
          cd ./day$(date +%d)
          touch answers.txt
          touch day$(date +%d).txt
          touch day$(date +%d).py
          curl -o input.txt 'https://adventofcode.com/2024/day/$(date +%d)/input' \
          -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
          -H 'accept-language: en-US,en;q=0.9' \
            -H 'cache-control: max-age=0' \
            -H 'cookie: session=53616c7465645f5f6d8380504a81fb5c2aae0e5c0e67e2a9a48bc15ce93a4ecdf96ce645d55264f0b61526733be709a16c341506a50dbf3c2202ba6baf36ae22' \
            -H 'priority: u=0, i' \
            -H 'referer: https://adventofcode.com/2024/day/17' \
            -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "macOS"' \
            -H 'sec-fetch-dest: document' \
            -H 'sec-fetch-mode: navigate' \
            -H 'sec-fetch-site: same-origin' \
            -H 'sec-fetch-user: ?1' \
            -H 'upgrade-insecure-requests: 1' \
            -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Day day$(date +%d) Created"
          git push
