name: Ruff
on: [push, pull_request]
jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install ruff
        run: |
          pip install ruff
      - name: ruff format
        run: |
          ruff format
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "GHA ruff formatted"
          git push