name: Ruff
on: [push, pull_request]
jobs:
  config-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install ruff
          git config user.name github-actions
          git config user.email github-actions@github.com
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "ruff format"
  push-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:
          git add .
          git commit -m "GHA ruff formatted"
          git push