name: Ruff
on: [push, pull_request]
jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for ruff changes
        id: check_tree
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "{dirty}={1}" >> $GITHUB_ENV
          else
            echo "{dirty}={0}" >> $GITHUB_ENV
          fi
          echo "$GITHUB_CONTEXT"

      - name: Autoformat and push changes
        if: ${{ env.DIRTY == '1' }}
        run: |
          pip install ruff
          ruff format
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "GHA ruff formatted"
          git push

      - name: No autoformatting done
        if: ${{ env.DIRTY != '1' }}
        run: |
          echo "Working tree is clean, autoformat not required."