name: Ruff
on: [push, pull_request]
jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Autoformat
        run: |
          pip install ruff
          ruff format
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .

      - name: Check for ruff changes
        id: check_tree
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "IS_DIRTY=true" >> "$GITHUB_ENV"
          else
            echo "IS_DIRTY=false" >> "$GITHUB_ENV"
          fi

      - name: Get tree status
        run: |
          echo "Ruff changes made: ${{ env.IS_DIRTY == 'true' }}"

      - name: Commit and push
        if: ${{ env.IS_DIRTY == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "GHA ruff formatted"
          git push

      - name: No autoformatting done
        if: ${{ env.IS_DIRTY != 'true' }}
        run: |
          echo "Working tree is clean, autoformat not required."