name: Ruff
on: [push, pull_request]
jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for ruff changes
        id: check_tree
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "dirty=true" >> "$GITHUB_OUTPUT"
          else
            echo "dirty=false" >> "$GITHUB_OUTPUT"
          fi
          echo ${{ steps.check_tree.outputs.dirty }}

      - name: Get tree status
        env:
          IS_DIRTY: ${{ steps.check_tree.outputs.dirty }}
        run: |
          echo "Ruff changes made: $IS_DIRTY"

      - name: Autoformat and push changes
        if: ${{ env.IS_DIRTY == 'true' }}
        run: |
          pip install ruff
          ruff format
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "GHA ruff formatted"
          git push

      - name: No autoformatting done
        env:
          IS_DIRTY: ${{ steps.check_tree.outputs.dirty }}
        if: ${{ env.IS_DIRTY != 'true' }}
        run: |
          echo "Working tree is clean, autoformat not required."