name: Ruff
on: [push, pull_request]
jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install ruff
          ruff format
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AUTO updated sequence number"
          git push